kind: BuildConfig
apiVersion: v1
metadata:
  name: demo-sample-build
spec:
  runPolicy: Serial
  triggers: 
      type: GitHub
      github:
        secret: secret101
  source: 
    git:
      uri: https://github.com/openshift/ruby-hello-world
  strategy: 
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.3
        namespace: openshift
  output: 
    to:
      kind: ImageStreamTag
      name: demo-is:latest