apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-bc
  namespace: demo
spec:
  source: 
    git:
      uri: https://github.com/KimiQianMin/openshift-demo.git
  strategy: 
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.3
        namespace: openshift
  output: 
    to:
      kind: ImageStreamTag
      name: demo-is:latest